# Generated by Django 4.2.2 on 2023-06-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_foods", "0002_food_description_food_special_price_and_more"),
        ("app_general", "0002_subscription_food"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="food",
        ),
        migrations.AddField(
            model_name="subscription",
            name="food_set",
            field=models.ManyToManyField(to="app_foods.food"),
        ),
    ]
